#! /bin/sh

if xdo id -a "$PANEL_WM_NAME" > /dev/null ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config top_padding $PANEL_HEIGHT
bspc subscribe report > "$PANEL_FIFO" &
$HOME/.config/lemonscripts/battery.sh > "$PANEL_FIFO" &
$HOME/.config/lemonscripts/clock.sh > "$PANEL_FIFO" &
$HOME/.config/lemonscripts/mail.sh > "$PANEL_FIFO" &
$HOME/.config/lemonscripts/wifi.sh > "$PANEL_FIFO" &
$HOME/.config/lemonscripts/vpn.sh > "$PANEL_FIFO" &
$HOME/.config/lemonscripts/vol.sh > "$PANEL_FIFO" &
$HOME/.config/lemonscripts/desktop.sh > "$PANEL_FIFO" &
$HOME/.config/lemonscripts/weather.sh > "$PANEL_FIFO" &
xtitle -sf "T%s\n" > "$PANEL_FIFO" &

. ./panel_colors

./panel_bar < "$PANEL_FIFO" | lemonbar -a 32 -u 2 -n "$PANEL_WM_NAME" -g x$PANEL_HEIGHT -o -4 -f "$PANEL_FONT_ICONS" -o -2 -f "$PANEL_FONT" -o 0 -f "$PANEL_FONT_JP" -F "$COLOR_FG" -B "$COLOR_BG" | sh &

wid=$(xdo id -a "$PANEL_WM_NAME")
tries_left=20
while [ -z "$wid" -a "$tries_left" -gt 0 ] ; do
	sleep 0.05
	wid=$(xdo id -a "$PANEL_WM_NAME")
	tries_left=$((tries_left - 1))
done
[ -n "$wid" ] && xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" "$wid"

echo $$ > /tmp/panel-pid

wait
