#!/bin/sh

sxhkd &

source $HOME/.config/colors/default

#bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor -d "一" "二"	"三"	"四"	"五"	"六"	"七"	"八"	"九" "十"
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width			4
bspc config window_gap				10

bspc config normal_border_color		"$bblk"
bspc config focused_border_color	"$red"

bspc config urgent_border_color     "$grn"

bspc config presel_feedback_color	"$red"

bspc config click_to_focus			button1

bspc config split_ratio				0.5
bspc config borderless_monocle		false
bspc config gapless_monocle			false

cd $HOME/.config/panel/ && ./panel &
